
CREATE TABLE IF NOT EXISTS `DCDominoLibModulesListStructure` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniqueId` int(11) NOT NULL,
  `status` int(11) NOT NULL,
  `developer` varchar(255) DEFAULT NULL,
  `module` varchar(255) DEFAULT NULL,
  `elementDeveloper` varchar(255) NOT NULL,
  `element` varchar(255) DEFAULT NULL,
  `ordem` int(11) DEFAULT NULL,
  `width` varchar(255) DEFAULT NULL,
  `hide` varchar(255) DEFAULT NULL,
  `clickable` int(11) DEFAULT NULL,
  `structureType` varchar(255) DEFAULT NULL,
  `structureName` varchar(255) NOT NULL,
  `sortable` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=412 ;

INSERT INTO `DCDominoLibModulesListStructure` (`id`, `uniqueId`, `status`, `developer`, `module`, `elementDeveloper`, `element`, `ordem`, `width`, `hide`, `clickable`, `structureType`, `structureName`, `sortable`) VALUES
(3, 1, 1, 'Domino', 'Languages', 'Domino', 'lang', 1, '5%', NULL, 1, 'varchar', '', 1),
(4, 3, 1, 'Domino', 'Languages', 'Domino', 'iso31662', 3, '10%', NULL, 0, 'varchar', '', 1),
(5, 1, 1, 'Domino', 'SiteTitle', 'Domino', 'name', 1, NULL, NULL, 1, 'varchar', '', 1),
(6, 1, 1, 'Domino', 'SiteTitle', 'Domino', 'description', 1, NULL, NULL, 1, 'text', '', 1),
(11, 1, 1, 'Domino', 'Content', 'Domino', 'name', 1, '', NULL, 1, 'varchar', '', 1),
(20, 4, 1, 'Domino', 'Languages', 'Domino', 'iso6392', 4, '10%', NULL, 0, 'varchar', '', 0),
(25, 1, 1, 'Domino', 'Menu', 'Domino', 'id', 1, '10%', NULL, 0, 'varchar', '', 0),
(26, 2, 1, 'Domino', 'Menu', 'Domino', 'name', 2, '', NULL, 1, 'varchar', '', 0),
(29, 1, 1, 'Domino', 'Translations', 'Domino', 'id', 1, '20%', NULL, 0, 'varchar', '', 0),
(30, 2, 1, 'Domino', 'Translations', 'Domino', 'name', 2, '', NULL, 1, 'varchar', '', 0),
(33, 1, 1, 'Domino', 'Users', 'Domino', 'firstname', 1, '', NULL, 1, 'varchar', '', 0),
(34, 2, 1, 'Domino', 'Users', 'Domino', 'surname', 2, '', NULL, 1, 'varchar', '', 0),
(35, 3, 1, 'Domino', 'Users', 'Domino', 'email', 3, '', NULL, 1, 'varchar', '', 0),
(36, 4, 1, 'Domino', 'Users', 'Domino', 'username', 4, '', NULL, 1, 'varchar', '', 0),
(37, 1, 1, 'Domino', 'LibModulesElements', 'Domino', 'developer', 1, '', NULL, 1, 'varchar', '', 0),
(38, 2, 1, 'Domino', 'LibModulesElements', 'Domino', 'element', 2, '', NULL, 1, 'varchar', '', 0),
(39, 3, 1, 'Domino', 'LibModulesElements', 'Domino', 'colType', 3, '', NULL, 1, 'varchar', '', 0),
(40, 4, 1, 'Domino', 'LibModulesElements', 'Domino', 'colLength', 4, '', NULL, 1, 'varchar', '', 0),
(41, 5, 1, 'Domino', 'LibModulesElements', 'Domino', 'icon', 5, '', NULL, 1, 'varchar', '', 0),
(42, 6, 1, 'Domino', 'LibModulesElements', 'Domino', 'structureType', 6, '', NULL, 1, 'varchar', '', 0),
(43, 8, 1, 'Domino', 'LibModulesElements', 'Domino', 'defaultVal', 8, '', NULL, 1, 'varchar', '', 0),
(44, 1, 1, 'Domino', 'LibModulesElementsNames', 'Domino', 'developer', 1, '', NULL, 1, 'varchar', '', 0),
(45, 2, 1, 'Domino', 'LibModulesElementsNames', 'Domino', 'element', 2, '', NULL, 1, 'varchar', '', 0),
(46, 3, 1, 'Domino', 'LibModulesElementsNames', 'Domino', 'name', 3, '', NULL, 1, 'varchar', '', 0),
(47, 7, 1, 'Domino', 'LibModulesElements', 'Domino', 'validation', 7, '', NULL, 1, 'varchar', '', 0),
(48, 1, 1, 'Domino', 'Timestamps', 'Domino', 'developer', 1, '', NULL, 1, 'varchar', '', 0),
(49, 2, 1, 'Domino', 'Timestamps', 'Domino', 'module', 2, '', NULL, 1, 'varchar', '', 0),
(50, 3, 1, 'Domino', 'Timestamps', 'Domino', 'id', 3, '', NULL, 1, 'varchar', '', 0),
(51, 4, 1, 'Domino', 'Timestamps', 'Domino', 'dateCreated', 4, '', NULL, 1, 'varchar', '', 0),
(52, 5, 1, 'Domino', 'Timestamps', 'Domino', 'userId', 5, '', NULL, 1, 'varchar', '', 0),
(53, 1, 1, 'Domino', 'UsersLoginLog', 'Domino', 'userId', 1, '', NULL, 0, 'varchar', '', 0),
(54, 2, 1, 'Domino', 'UsersLoginLog', 'Domino', 'dateCreated', 2, '', NULL, 0, 'varchar', '', 0),
(55, 3, 1, 'Domino', 'UsersLoginLog', 'Domino', 'dateEnd', 3, '', NULL, 0, 'varchar', '', 0),
(70, 2, 1, 'Domino', 'Languages', 'Domino', 'name', 2, '', NULL, 1, 'varchar', '', 0),
(83, 1, 1, 'Domino', 'Keywords', 'Domino', 'keyword', 1, '', NULL, 1, 'varchar', '', 0),
(87, 1, 1, 'Domino', 'ContentBlocks', 'Domino', 'name', 1, '', NULL, 1, 'varchar', '', 0),
(88, 2, 1, 'Domino', 'ContentBlocks', 'Domino', 'content', 2, '', NULL, 1, 'text', '', 0),
(107, 1, 1, 'Domino', 'Pictures', 'Domino', 'filename', 1, '20%', NULL, 1, 'picture', '', 0),
(108, 2, 1, 'Domino', 'Pictures', 'Domino', 'name', 2, '', NULL, 1, 'varchar', '', 0),
(109, 1, 1, 'Domino', 'Files', 'Domino', 'name', 1, '', NULL, 1, 'varchar', '', 0),
(110, 3, 1, 'Domino', 'SiteTitle', 'Domino', 'author', 3, '', NULL, 1, 'varchar', '', 0),
(114, 3, 1, 'Domino', 'Content', 'Domino', 'privacy', 3, '', NULL, 0, 'bool', '', 0),
(115, 4, 1, 'Domino', 'Content', 'Domino', 'ghost', 4, '', NULL, 0, 'bool', '', 0),
(121, 1, 1, 'Domino', 'SiteCrossPictures', 'Domino', 'entry', 1, '', NULL, 1, 'varchar', '', 0),
(122, 2, 1, 'Domino', 'SiteCrossPictures', 'Domino', 'entryRel', 2, '', NULL, 1, 'varchar', '', 0),
(123, 1, 1, 'Domino', 'SiteCross', 'Domino', 'entry', 1, '', NULL, 1, 'varchar', '', 0),
(124, 2, 1, 'Domino', 'SiteCross', 'Domino', 'entryRel', 2, '', NULL, 1, 'varchar', '', 0),
(125, 3, 1, 'Domino', 'SiteCrossPictures', 'Domino', 'picProfile', 3, '', NULL, 1, 'bool', '', 0),
(126, 4, 1, 'Domino', 'SiteCrossPictures', 'Domino', 'picCover', 4, '', NULL, 1, 'bool', '', 0),
(130, 4, 1, 'Domino', 'ContentBlocks', 'Domino', 'theme', 4, '', NULL, 0, 'varchar', '', 0),
(133, 1, 1, 'Domino', 'Slideshow', 'Domino', 'name', 2, '', NULL, 1, 'varchar', '', 0),
(134, 2, 1, 'Domino', 'Slideshow', 'Domino', 'dateStart', 3, '10%', NULL, 0, 'date', '', 0),
(135, 3, 1, 'Domino', 'Slideshow', 'Domino', 'dateEnd', 3, '10%', NULL, 0, 'date', '', 0),
(136, 1, 1, 'Domino', 'SlideshowSlides', 'Domino', 'name', 4, '', NULL, 1, 'varchar', '', 0),
(137, 2, 1, 'Domino', 'SlideshowSlides', 'Domino', 'dateStart', 2, '10%', NULL, 0, 'date', '', 0),
(138, 3, 1, 'Domino', 'SlideshowSlides', 'Domino', 'dateEnd', 3, '10%', NULL, 0, 'date', '', 0),
(142, 4, 1, 'Domino', 'Slideshow', 'Domino', 'id', 1, '20%', NULL, 0, 'varchar', '', 0),
(146, 3, 1, 'Domino', 'ContentBlocks', 'Domino', 'component', 2, '', NULL, 0, 'varchar', '', 0),
(153, 1, 1, 'Domino', 'Courses', 'Domino', 'id', 1, '10%', NULL, 0, 'varchar', '', 0),
(154, 2, 1, 'Domino', 'Courses', 'Domino', 'name', 2, '', NULL, 1, 'varchar', '', 0),
(161, 1, 1, 'Domino', 'ViewsStructure', 'Domino', 'viewDeveloper', 1, '15%', NULL, 0, 'varchar', '', 0),
(162, 2, 1, 'Domino', 'view', 'Domino', 'component', 2, '', NULL, 1, 'varchar', '', 0),
(163, 3, 1, 'Domino', 'ViewsStructure', 'Domino', 'developer', 3, '', NULL, 0, 'varchar', '', 0),
(164, 3, 1, 'Domino', 'ViewsStructure', 'Domino', 'component', 5, '', NULL, 1, 'varchar', '', 0),
(167, 1, 1, 'Domino', 'Themes', 'Domino', 'developer', 1, '15%', NULL, 1, 'varchar', '', 0),
(168, 2, 1, 'Domino', 'Themes', 'Domino', 'theme', 2, '', NULL, 1, 'varchar', '', 0),
(171, 3, 1, 'Domino', 'ContentBlocks', 'Domino', 'type', 3, '', NULL, 0, 'varchar', '', 0),
(183, 1, 1, 'Domino', 'HeaderContact', 'Domino', 'name', 1, '', NULL, 1, 'varchar', '', 0),
(184, 2, 1, 'Domino', 'HeaderContact', 'Domino', 'type', 2, '', NULL, 0, 'varchar', '', 0),
(185, 3, 1, 'Domino', 'HeaderContact', 'Domino', 'icon', 3, '', NULL, 0, 'varchar', '', 0),
(186, 4, 1, 'Domino', 'HeaderContact', 'Domino', 'url', 4, '', NULL, 0, 'varchar', '', 0),
(251, 1, 1, 'Domino', 'Items', 'Domino', 'developer', 1, '10%', NULL, 1, 'varchar', '', 0),
(252, 2, 1, 'Domino', 'Items', 'Domino', 'item', 2, '', NULL, 1, 'varchar', '', 0),
(254, 1, 1, 'Domino', 'ItemsSubitems', 'Domino', 'developer', 1, '15%', NULL, 1, 'varchar', '', 0),
(255, 2, 1, 'Domino', 'ItemsSubitems', 'Domino', 'item', 2, '15%', NULL, 1, 'varchar', '', 0),
(256, 3, 1, 'Domino', 'ItemsSubitems', 'Domino', 'subitem', 3, '', NULL, 1, 'varchar', '', 0),
(257, 4, 1, 'Domino', 'ItemsSubitems', 'Domino', 'type', 4, '10%', NULL, 0, 'varchar', '', 0),
(259, 1, 1, 'Domino', 'ItemsComponents', 'Domino', 'developer', 1, '15%', NULL, 1, 'varchar', '', 0),
(260, 2, 1, 'Domino', 'ItemsComponents', 'Domino', 'item', 2, '15%', NULL, 1, 'varchar', '', 0),
(261, 3, 1, 'Domino', 'ItemsComponents', 'Domino', 'component', 3, '', NULL, 1, 'varchar', '', 0),
(262, 4, 1, 'Domino', 'ItemsComponents', 'Domino', 'type', 4, '', NULL, 0, 'varchar', '', 0),
(264, 1, 1, 'Domino', 'Views', 'Domino', 'developer', 1, '15%', NULL, 1, 'varchar', '', 0),
(265, 2, 1, 'Domino', 'Views', 'Domino', 'view', 2, '', NULL, 1, 'varchar', '', 0),
(267, 1, 1, 'Domino', 'ViewsStructure', 'Domino', 'view', 2, '15%', NULL, 0, 'varchar', '', 0),
(272, 1, 1, 'Domino', 'LibThemes', 'Domino', 'developer', 1, '15%', NULL, 0, 'varchar', '', 0),
(273, 2, 1, 'Domino', 'LibThemes', 'Domino', 'id', 2, '', NULL, 1, 'varchar', '', 0),
(303, 1, 1, 'Domino', 'LibItemsSubitems', 'Domino', 'developer', 1, '10%', NULL, 0, 'varchar', '', 0),
(304, 2, 1, 'Domino', 'LibItemsSubitems', 'Domino', 'item', 2, '20%', NULL, 0, 'varchar', '', 0),
(305, 3, 1, 'Domino', 'LibItemsSubitems', 'Domino', 'subitem', 3, '', NULL, 1, 'varchar', '', 0),
(306, 4, 1, 'Domino', 'LibItemsSubitems', 'Domino', 'type', 4, '10%', NULL, 0, 'varchar', '', 0),
(308, 1, 1, 'Domino', 'LibItems', 'Domino', 'developer', 1, '15%', NULL, 0, 'varchar', '', 0),
(309, 2, 1, 'Domino', 'LibItems', 'Domino', 'item', 2, '', NULL, 1, 'varchar', '', 0),
(311, 4, 1, 'Domino', 'LibItems', '', '', 4, '', NULL, 0, 'deploy', '', 0),
(312, 4, 1, 'Domino', 'LibThemes', '', '', 4, '', NULL, 0, 'deploy', '', 0),
(368, 1, 1, 'Domino', 'Modules', 'Domino', 'developer', 1, '20%', NULL, 1, 'varchar', '', 0),
(369, 2, 1, 'Domino', 'Modules', 'Domino', 'module', 2, '', NULL, 1, 'varchar', '', 0),
(371, 1, 1, 'Domino', 'ModulesCrossed', 'Domino', 'developer', 1, '15%', NULL, 0, 'varchar', '', 0),
(372, 2, 1, 'Domino', 'ModulesCrossed', 'Domino', 'module', 2, '15%', NULL, 0, 'varchar', '', 0),
(373, 3, 1, 'Domino', 'ModulesCrossed', 'Domino', 'developerRel', 3, '15%', NULL, 1, 'varchar', '', 0),
(374, 4, 1, 'Domino', 'ModulesCrossed', 'Domino', 'moduleRel', 4, '', NULL, 1, 'varchar', '', 0),
(382, 1, 1, 'Domino', 'Developers', 'Domino', 'name', 1, '', NULL, 1, 'varchar', '', 0),
(383, 2, 1, 'Domino', 'Developers', 'Domino', 'username', 2, '20%', NULL, 0, 'varchar', '', 0),
(384, 3, 1, 'Domino', 'Developers', 'Domino', 'email', 3, '20%', NULL, 0, 'varchar', '', 0),
(390, 1, 1, 'Domino', 'UsersLoginFail', 'Domino', 'username', 1, '', NULL, 0, 'varchar', '', 0),
(391, 2, 1, 'Domino', 'UsersLoginFail', 'Domino', 'userId', 2, '', NULL, 0, 'varchar', '', 0),
(392, 3, 1, 'Domino', 'UsersLoginFail', 'Domino', 'dateCreated', 3, '', NULL, 0, 'date', '', 0),
(393, 1, 1, 'Domino', 'IdentityDomains', 'Domino', 'domain', 1, '', NULL, 1, 'varchar', '', 0),
(394, 2, 1, 'Domino', 'IdentityDomains', 'Domino', 'languages', 2, '', NULL, 0, 'varchar', '', 0),
(395, 3, 1, 'Domino', 'IdentityDomains', 'Domino', 'lang', 3, '', NULL, 0, 'varchar', '', 0),
(396, 4, 1, 'Domino', 'IdentityDomains', 'Domino', 'langMain', 4, '', NULL, 0, 'varchar', '', 0),
(397, 5, 1, 'Domino', 'IdentityDomains', 'Domino', 'urltype', 5, '', NULL, 0, 'varchar', '', 0),
(398, 6, 1, 'Domino', 'IdentityDomains', 'Domino', 'urlLangStandard', 6, '', NULL, 0, 'varchar', '', 0),
(399, 7, 1, 'Domino', 'IdentityDomains', 'Domino', 'protocol', 7, '', NULL, 0, 'varchar', '', 0),
(400, 1, 1, 'Domino', 'LibItemsComponents', 'Domino', 'developer', 1, '', NULL, 1, 'varchar', '', 0),
(401, 2, 1, 'Domino', 'LibItemsComponents', 'Domino', 'item', 2, '', NULL, 1, 'varchar', '', 0),
(402, 3, 1, 'Domino', 'LibItemsComponents', 'Domino', 'component', 3, '', NULL, 1, 'varchar', '', 0),
(403, 4, 1, 'Domino', 'LibItemsComponents', 'Domino', 'type', 4, '', NULL, 0, 'varchar', '', 0),
(404, 5, 1, 'Domino', 'LibItemsComponents', 'Domino', 'included', 5, '', NULL, 0, 'varchar', '', 0);
