CREATE TABLE IF NOT EXISTS `DCDominoLanguages` (
  `lang` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `iso31662` varchar(255) DEFAULT NULL,
  `iso6392` varchar(255) NOT NULL,
  KEY `id` (`lang`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `DCDominoLanguages` (`lang`, `name`, `iso31662`, `iso6392`) VALUES
('sl', 'Slovensko', 'si', 'slv'),
('en', 'English', 'en', 'eng'),
('de', 'Deutsch', 'de', 'deu'),
('hr', 'Hrvaški', 'hr', 'hrv'),
('us', 'US English', 'us', ''),
('fr', 'Français', 'fr', 'fra'),
('it', 'Italiano', 'it', 'ita'),
('ru', 'Russian', 'ru', 'rus'),
('es', 'Español', 'es', 'spa'),
('pt', 'Portuguese', 'pt', 'por'),
('uk', 'Ukraine', 'uk', 'ukr'),
('tr', 'Turkish', 'tr', 'tur'),
('ar', 'Arabic', 'ar', 'ara'),
('cs', 'Čeština', 'cz', 'cze'),
('mt', 'Maltese', 'mt', 'mlt'),
('111', 'Abkhazian', '', 'abk'),
('ab', 'Abkhazian', '', 'abk'),
('af', 'Afrikaans', '', 'afr'),
('ak', 'Akan', '', 'aka'),
('sq', 'Albanian', 'al', 'alb'),
('am', 'Amharic', '', 'amh'),
('an', 'Aragonese', '', 'arg'),
('hy', 'Armenian', 'am', 'arm'),
('as', 'Assamese', '', 'asm'),
('av', 'Avaric', '', 'ava'),
('ae', 'Avestan', '', 'ave'),
('ay', 'Aymara', '', 'aym'),
('az', 'Azerbaijani', 'az', 'aze'),
('ba', 'Bashkir', '', 'bak'),
('nm', 'Bambara', '', 'bam'),
('eu', 'Basque', '', 'baq'),
('be', 'Belarusian', 'by', 'bel'),
('bn', 'Bengali', '', 'ben'),
('bh', 'Bihari languages', '', 'bih'),
('bi', 'Bislama', '', 'bis'),
('bo', 'Tibetan', '', 'bod'),
('bs', 'Bosnian', 'ba', 'bos'),
('br', 'Breton', '', 'bre'),
('bg', 'Bulgarian', 'bg', 'bul'),
('my', 'Burmese', '', 'bur'),
('cs', 'Czech', 'cz', 'cs'),
('ca', 'Catalan; Valencian', '', 'cat'),
('ch', 'Chamorro', '', 'cha'),
('ce', 'Chechen', 'ru-ce', 'che'),
('zh', 'Chinese', 'chi', 'chi'),
('cu', 'church slavic', '', 'chu'),
('cv', 'Chuvash', '', 'chv'),
('kw', 'Cornish', 'cor', 'kw'),
('cr', 'Cree', '', 'cre'),
('co', 'Corsican', '', 'cos'),
('cy', 'Welsh', '', 'cym'),
('da', 'Danish', 'dk', 'dan'),
('dv', 'Dhivehi', 'mv', 'div'),
('nl', 'Dutch', 'nl', 'dut'),
('dz', 'Dzongkha', 'bt', 'dzo'),
('el', 'Modern Greek', 'gr', 'ell'),
('eo', 'Esperanto', '', 'epo'),
('et', 'Estonian', 'ee', 'est'),
('ee', 'Ewe', '', 'ewe'),
('fo', 'Faroese', '', 'fao'),
('fa', 'Persian', '', 'fas'),
('fj', 'Fijian', 'fj', 'fij'),
('fi', 'Finnish', 'fi', 'fin'),
('fr', 'French', 'fr', 'fra'),
('fy', 'Western Frisian', '', 'fry'),
('ff', 'Fulah', '', 'ful'),
('ka', 'Georgian', 'ge', 'geo'),
('gd', 'Gaelic; Scottish Gaelic', '', 'gla'),
('ga', 'Irish', 'ie', 'gle'),
('gl', 'Galician', '', 'glg'),
('gv', 'Manx', '', 'glv'),
('gn', 'Guarani', '', 'grn'),
('gu', 'Gujarati', '', 'guj'),
('ht', 'Haitian; Haitian Creole', 'ht', 'hat'),
('ha', 'Hausa', '', 'hau'),
('he', 'Hebrew', '', 'heb'),
('hz', 'Herero', '', 'her'),
('hi', 'Hindi', 'in', 'hin'),
('ho', 'Hiri Motu', 'pg', 'hmo'),
('hu', 'Hungarian', 'hu', 'hun'),
('ig', 'Igbo', 'ng', 'ibo'),
('is', 'Icelandic', 'is', 'ice'),
('io', 'Ido', '', 'ido'),
('ii', 'Sichuan Yi; Nuosu', '', 'iii'),
('iu', 'Inuktitut', '', 'iku'),
('ie', 'Interlingue; Occidental', '', 'ile'),
('ia', 'Interlingua', '', 'ina'),
('id', 'Indonesian', 'id', 'ind'),
('ik', 'Inupiaq', '', 'ipk'),
('jv', 'Javanese', '', 'jav'),
('ja', 'Japanese', 'jp', 'jpn'),
('kl', 'Kalaallisut; Greenlandic', '', 'kal'),
('kn', 'Kannada', 'id', 'kan'),
('ks', 'Kashmiri', '', 'kas'),
('kr', 'Kanuri', '', 'kau');