
CREATE TABLE IF NOT EXISTS `DCDominoLibModulesColsMain` (
  `developer` varchar(255) NOT NULL,
  `module` varchar(255) NOT NULL,
  `elementDeveloper` varchar(255) NOT NULL,
  `element` varchar(255) NOT NULL,
  `ordem` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `DCDominoLibModulesColsMain` (`developer`, `module`, `elementDeveloper`, `element`, `ordem`) VALUES
('Domino', 'LibModulesElements', 'Domino', 'developer', 1),
('Domino', 'LibModulesElements', 'Domino', 'element', 2),
('Domino', 'LibModulesElementsNames', 'Domino', 'developer', 1),
('Domino', 'LibModulesElementsNames', 'Domino', 'element', 2),
('Domino', 'IdentityLanguages', 'Domino', 'lang', 1),
('Domino', 'Content', 'Domino', 'id', 1),
('Domino', 'Languages', 'Domino', 'lang', 1),
('Domino', 'Users', 'Domino', 'id', 1),
('Domino', 'Keywords', 'Domino', 'id', 1),
('Domino', 'Menu', 'Domino', 'id', 1),
('Domino', 'ContentBlocks', 'Domino', 'id', 1),
('Domino', 'Files', 'Domino', 'id', 1),
('Domino', 'Pictures', 'Domino', 'id', 1),
('Domino', 'SiteTitle', 'Domino', 'id', 1),
('Domino', 'Translations', 'Domino', 'id', 1),
('Domino', 'SiteCrossPictures', 'Domino', 'entry', 1),
('Domino', 'SiteCrossPictures', 'Domino', 'entryRel', 2),
('Domino', 'SiteCross', 'Domino', 'entry', 1),
('Domino', 'SiteCross', 'Domino', 'entryRel', 2),
('Domino', 'Slideshow', 'Domino', 'id', 1),
('Domino', 'SlideshowSlides', 'Domino', 'id', 1),
('Domino', 'ViewsStructure', 'Domino', 'developer', 1),
('Domino', 'Themes', 'Domino', 'developer', 1),
('Domino', 'Themes', 'Domino', 'theme', 2),
('Domino', 'HeaderContact', 'Domino', 'id', 1),
('Domino', 'Items', 'Domino', 'developer', 1),
('Domino', 'Items', 'Domino', 'item', 2),
('Domino', 'ItemsSubitems', 'Domino', 'developer', 1),
('Domino', 'ItemsSubitems', 'Domino', 'item', 2),
('Domino', 'ItemsSubitems', 'Domino', 'subitem', 3),
('Domino', 'ItemsComponents', 'Domino', 'developer', 1),
('Domino', 'ItemsComponents', 'Domino', 'item', 2),
('Domino', 'ItemsComponents', 'Domino', 'component', 3),
('Domino', 'Views', 'Domino', 'developer', 1),
('Domino', 'Views', 'Domino', 'view', 2),
('Domino', 'ViewsStructure', 'Domino', 'component', 2),
('Domino', 'LibThemes', 'Domino', 'developer', 1),
('Domino', 'LibThemes', 'Domino', 'id', 2),
('Domino', 'LibItemsSubitems', 'Domino', 'developer', 1),
('Domino', 'LibItemsSubitems', 'Domino', 'item', 2),
('Domino', 'LibItemsSubitems', 'Domino', 'subitem', 3),
('Domino', 'LibItems', 'Domino', 'developer', 1),
('Domino', 'LibItems', 'Domino', 'item', 2),
('Domino', 'Modules', 'Domino', 'developer', 1),
('Domino', 'Modules', 'Domino', 'module', 2),
('Domino', 'Identity', 'Domino', 'id', 1),
('Domino', 'ModulesCrossed', 'Domino', 'id', 1),
('Domino', 'Developers', 'Domino', 'id', 1),
('Domino', 'UsersLoginFail', 'Domino', 'userId', 1),
('Domino', 'UsersLoginFail', 'Domino', 'dateCreated', 2),
('Domino', 'SiteSlugs', 'Domino', 'entry', 1),
('Domino', 'LibItemsComponents', 'Domino', 'developer', 1),
('Domino', 'LibItemsComponents', 'Domino', 'item', 2),
('Domino', 'LibItemsComponents', 'Domino', 'component', 3);
