

CREATE TABLE IF NOT EXISTS `DCDominoLibModules` (
  `module` varchar(255) NOT NULL,
  `developer` varchar(255) DEFAULT NULL,
  `siteIndex` int(11) NOT NULL,
  `queryOrderBy` varchar(255) NOT NULL,
  `querySort` varchar(255) NOT NULL,
  `parent` varchar(255) DEFAULT NULL,
  `sort_cats` varchar(255) NOT NULL,
  `data_return` varchar(255) NOT NULL,
  `default_privacy` int(11) NOT NULL,
  `cross_type` int(11) NOT NULL,
  `filter_fields` varchar(255) NOT NULL,
  `status_module` int(11) NOT NULL,
  `col_main` varchar(255) NOT NULL,
  `addType` int(11) NOT NULL,
  `increment` varchar(255) NOT NULL,
  `ver` varchar(255) NOT NULL,
  `ver_id` int(11) NOT NULL,
  `colName` varchar(255) NOT NULL,
  `moduleType` varchar(255) NOT NULL,
  UNIQUE KEY `id` (`module`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `DCDominoLibModules` (`module`, `developer`, `siteIndex`, `queryOrderBy`, `querySort`, `parent`, `sort_cats`, `data_return`, `default_privacy`, `cross_type`, `filter_fields`, `status_module`, `col_main`, `addType`, `increment`, `ver`, `ver_id`, `colName`, `moduleType`) VALUES
('SiteTitle', 'Domino', 1, 'id', 'ASC', '0', '', '', 0, 0, '', 0, 'id', 0, '1', '', 1, 'name', 'index'),
('Content', 'Domino', 0, 'id', 'ASC', NULL, '', '', 0, 0, '', 0, 'id', 0, '1', '', 0, 'name', 'index'),
('IdentityLanguages', 'Domino', 1, 'ordem', 'ASC', '0', '', '', 0, 0, '', 0, 'lang', 0, '1', '', 0, 'lang', 'index'),
('LibModules', 'Domino', 0, '', '', NULL, '', '', 0, 0, '', 0, '', 0, '', '', 0, 'name', 'index'),
('LibModulesStructureTypes', 'Domino', 0, 'id', 'ASC', NULL, '', '', 0, 0, '', 0, 'id', 0, '', '', 0, 'name', 'index'),
('Menu', 'Domino', 0, 'order', 'ASC', NULL, '', '', 0, 0, '', 0, 'id', 0, '', '', 0, 'name', 'index'),
('Identity', 'Domino', 0, '', '', NULL, '', '', 0, 0, '', 0, 'id', 0, '1', '', 0, 'name', 'noindex'),
('IdentityDomains', 'Domino', 0, 'domain', 'ASC', NULL, '', '', 0, 0, '', 0, 'domain', 0, '', '', 0, 'name', 'index'),
('LibModulesElements', 'Domino', 0, 'developer,element', 'ASC', NULL, '', '', 0, 0, '', 0, 'developer,element', 0, '', '', 0, 'name', 'noindex'),
('Translations', 'Domino', 0, 'name', 'ASC', NULL, '', '', 0, 0, '', 0, 'id', 0, '', '', 0, 'name', 'noindex'),
('Users', 'Domino', 0, 'id', 'ASC', NULL, '', '', 0, 0, '', 0, 'id', 0, '1', '', 0, 'name', 'noindex'),
('LibModulesElementsNames', 'Domino', 0, 'developer,name', 'ASC', NULL, '', '', 0, 0, '', 0, 'developer,element', 0, '', '', 0, 'name', 'noindex'),
('Timestamps', 'Domino', 0, 'tstamp', 'DESC', NULL, '', '', 0, 0, '', 0, 'developer,module,id', 0, '', '1', 0, 'name', 'noindex'),
('UsersLoginLog', 'Domino', 0, 'dateCreated', 'DESC', NULL, '', '', 0, 0, '', 0, 'dateCreated', 0, '', '', 0, 'name', 'noindex'),
('Keywords', 'Domino', 0, 'keyword', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '1', '', 0, 'name', 'index'),
('ContentBlocks', 'Domino', 0, 'order', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '1', '', 0, 'name', 'index'),
('Contact', 'Domino', 0, 'order', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '1', '1', 0, 'name', 'index'),
('Pictures', 'Domino', 0, 'name', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '1', '1', 0, 'name', 'index'),
('Files', 'Domino', 0, 'name', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '1', '1', 0, 'name', 'index'),
('SiteCross', 'Domino', 0, 'entry', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '', '', 0, 'name', 'noindex'),
('SiteCrossPictures', 'Domino', 0, 'entry', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '', '', 0, 'name', 'noindex'),
('Slideshow', 'Domino', 0, 'dateEnd', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '0', '', 0, 'name', 'index'),
('SlideshowSlides', 'Domino', 0, 'dateEnd', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '1', '', 0, 'name', 'index'),
('ViewsStructure', 'Domino', 0, '`order`', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '', '', 0, 'name', 'noindex'),
('Design', 'Domino', 0, '', '', NULL, '', '', 0, 0, '', 0, '', 0, '', '', 0, 'name', ''),
('Themes', 'Domino', 0, 'theme', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '', '', 0, 'name', 'noindex'),
('HeaderContact', 'Domino', 0, 'ordem', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '1', '', 0, 'name', 'noindex'),
('Items', 'Domino', 0, 'item', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '', '1', 0, 'name', 'noindex'),
('ItemsSubitems', 'Domino', 0, 'item', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '', '1', 0, 'name', 'noindex'),
('ItemsComponents', 'Domino', 0, 'item', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '', '1', 0, 'name', 'noindex'),
('Views', 'Domino', 0, 'view', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '', '1', 0, 'name', 'noindex'),
('LibThemes', 'Domino', 0, 'id', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '', '', 0, 'name', 'noindex'),
('LibItemsSubitems', 'Domino', 0, 'item,subitem', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '', '', 0, 'name', 'noindex'),
('Lib', 'Domino', 0, '', '', NULL, '', '', 0, 0, '', 0, '', 0, '', '', 0, 'name', ''),
('LibItems', 'Domino', 0, 'item', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '', '1', 0, 'name', 'noindex'),
('Modules', 'Domino', 0, 'module', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '0', '', 0, '', 'noindex'),
('ModulesCrossed', 'Domino', 0, 'module', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '', '1', 0, '', 'noindex'),
('User', 'Domino', 0, 'id', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '', '1', 0, '', 'noindex'),
('Developers', 'Domino', 0, 'name', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '1', '1', 0, '', 'noindex'),
('UsersLoginFail', 'Domino', 0, 'dateCreated', 'DESC', NULL, '', '', 0, 0, '', 0, '', 0, '', '1', 0, '', 'noindex'),
('SiteIndex', 'Domino', 0, 'indexId', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '', '', 0, '', 'noindex'),
('SiteSlugs', 'Domino', 0, '', '', NULL, '', '', 0, 0, '', 0, '', 0, '', '1', 0, '', 'noindex'),
('LibItemsComponents', 'Domino', 0, 'item', 'ASC', NULL, '', '', 0, 0, '', 0, '', 0, '', '1', 0, '', 'noindex'),
('AdminContent', 'Domino', 0, 'id', 'ASC', NULL, '', '', 0, 0, '', 0, 'name', 0, '1', '1', 0, '', 'index'),
('AdminSiteIndex', 'Domino', 0, 'indexId', 'ASC', NULL, '', '', 0, 0, '', 0, 'name', 0, '1', '1', 0, '', 'noindex'),
('AdminSiteSlugs', 'Domino', 0, '', '', NULL, '', '', 0, 0, '', 0, '', 0, '', '1', 0, '', 'noindex');
